### PR TITLE
Update Dockerfile and API for transform PR

### PR DESCRIPTION
**Pull request by wjxiz1992**
Update environment setup due to https://github.com/NVIDIA/spark-rapids-ml/pull/19

Signed-off-by: Allen Xu <allxu@nvidia.com>

### CODE REVIEW

**Comment by nvliyuan** [comment]
Is this pr target to v21.10 or v21.12?

**Comment by wjxiz1992** [comment]
v21.12

**Comment by nvliyuan** [comment]
@wjxiz1992 I just create v21.12 branch, could you target the pr to v21.21?

**Comment by wjxiz1992** [comment]
Hi @nvliyuan, can you add @pxLi to reviewer list because this also has impacts on related CI job.

**Comment by nvliyuan** [comment]
@wjxiz1992 sure, added @pxLi

**Review by nvliyuan — APPROVED** [review]

**Pull request merged**
