### PR TITLE
Update the python notebooks for the customer churn examples

### PR DESCRIPTION
**Pull request by NvTimLiu**
1, Add the variables 'SPARK_MASTER_URL' and 'DATA_ROOT' to support automated testing from CI/CD jobs.
    
    2, 'output_prefix' is NOT referenced in below lines

image

### CODE REVIEW

**Comment by NvTimLiu** [comment]
Build PASS: 
image

**Comment by YanxuanLiu** [comment]
Does it still require same version for spark cluster and pyspark?

**Comment by NvTimLiu** [comment]
> Does it still require same version for spark cluster and pyspark?

Yes we need to keep the pyspark and spark-bin consistent, 

actually we only need to point the `PYTHON_PATH` to the current spark binary instead.

**Comment by YanxuanLiu** [comment]
> > Does it still require same version for spark cluster and pyspark?
> 
> Yes we need to keep the pyspark and spark-bin consistent,
> 
> actually we only need to point the `PYTHONPATH` to the current spark binary [export PYTHONPATH=$SPARK_HOME/python].

Can we avoid `spark session not found` error by pointing `PYTHONPATH` only but ignoring the pyspark version installed?

**Comment by NvTimLiu** [comment]
> > > Does it still require same version for spark cluster and pyspark?
> > 
> > 
> > Yes we need to keep the pyspark and spark-bin consistent,
> > actually we only need to point the `PYTHONPATH` to the current spark binary [export PYTHONPATH=$SPARK_HOME/python].
> 
> Can we avoid `spark session not found` error by pointing `PYTHONPATH` only but ignoring the pyspark version installed?

yes, right

**Review by YanxuanLiu — APPROVED** [review]
LGTM. We also need to update the README to introduce the environment we need to execute the notebook.

**Review by nvliyuan — APPROVED** [review]
LGTM

**Pull request merged**
