### PR TITLE
Add notebook for using qualification user tools in Databricks

### PR DESCRIPTION
**Pull request by parthosa**
Fixes https://github.com/NVIDIA/spark-rapids-tools/issues/571. This PR adds a new example notebook for using qualification user tools in Databricks

### Changes:

1. Added a new dropdown field `csp` to choose between `aws` and `azure` (defaults to `aws`).
2. Create a virtual environment and install `spark-rapids-user-tools`
3. Run qualification on user tools.
4. Parse the logs to store the output folder as a variable.

### Output: 

image

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

### CODE REVIEW

**Review by NvTimLiu — DISMISSED** [review]
LGTM

**Comment by nvliyuan** [comment]
Hi @parthosa , thanks for the contributing, could you help re-target the pr to branch-23.12?

**Comment by nvliyuan** [comment]
Hi @parthosa , seems the branch is still main.
And is the notebook specific to some Databricks runtime version?
I hit below error while running on 10.4ML:
image

**Comment by nvliyuan** [comment]
> I hit below error while running on 10.4ML:

The error will not show up if I run the cell for the second time. Another issue is FileNotFoundError, I checked the folder and confirmed there are output files in the dbfs, any idea?
image
image

**Comment by parthosa** [comment]
Thanks @nvliyuan. I have updated the base branch to `branch-23.12` and fixed the issues related to output folder: The notebook now creates a separate virtual environment and installs `spark-rapids-user-tools` package in it. See description for updated UI.

**Review by nvliyuan — APPROVED** [review]

**Comment by nvliyuan** [comment]
LGTM

**Pull request merged**
