### PR TITLE
[xgboost] Remove default parameters

### PR DESCRIPTION
**Pull request by wbo4958**
This PR tries to remove the default XGBoost parameters.

### CODE REVIEW

**Comment by nvliyuan** [comment]
why we need to remove these default params?

**Comment by nvliyuan** [comment]
should we also remove the same config in python-codes/notebooks-codes to keep consistent?

**Comment by wbo4958** [comment]
@nvliyuan The python code is deprecated for the new xgboost pyspark. I will submit the whole APP. so right now it's ok to just remove the default parameters of scala.

**Comment by wbo4958** [comment]
@GaryShen2008 @nvliyuan I just checked the notebook of scala and all the default parameters have already been removed.

**Comment by GaryShen2008** [comment]
Will this change impact the number in https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.10/examples/XGBoost-Examples/README.md?
If so, why do we change the config?

**Comment by nvliyuan** [comment]
> @GaryShen2008 @nvliyuan I just checked the notebook of scala and all the default parameters have already been removed.

I found a useless variable in mortgage/notebooks/scala/mortgage-ETL.ipynb:`val commParamMap`can you also help remove it? thanks

**Comment by wbo4958** [comment]
> Will this change impact the number in https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.10/examples/XGBoost-Examples/README.md? If so, why do we change the config?

I think there might be a slight affection for that figure since from what I tested, the performance for the default xgboost parameters should be better than the parameters hardcoded by the sample for the mortgage case (I didn't test taxi). 

BTW, the README seems just to list a final performance picture, which xgboost/rapids version and which parameters of xgboost, and which conf of spark can be used to repro it? Seems it's hard for user to repro this number.

BTW, seems this performance is tested by nvidia-internal-xgboost version instead of based on dmlc/xgboost. Please correct me. Since I remember I just had the PR switching the dependency from nvidia version to dmlc version. So from that point of view, I think removing parameters is not bad. On the other hand, The performance should be more meaningful for default parameters instead of tuning much, since some parameters may like GPU more, and vice versa.

**Comment by nvliyuan** [comment]
@GaryShen2008  I think we can merge this pr first, then I will file an issue and retest the xgboost performance, if the affection is not large, I will draft a pr to update(if there is no affection then no need to draft pr); if the affection is unexpected, we can revert this pr. Any insights?

**Comment by nvliyuan** [comment]
> BTW, seems this performance is tested by nvidia-internal-xgboost version instead of based on dmlc/xgboost. Please correct me.

@wbo4958 yes, the performance is based on xgboost4j_3.0-1.4.2-0.3.0; but changing the config still might have an affection; I will double check the perf result

**Review by nvliyuan — APPROVED** [review]

**Comment by wbo4958** [comment]
@GaryShen2008 any suggestions?

**Comment by GaryShen2008** [comment]
> @GaryShen2008 any suggestions?
Since Yuan accepts it, I'm ok with this PR.
The sample here is mainly to demonstrate the capability of xgboost training with GPU. It's not for the benchmark directly.
Anyway, removing some parameters makes it simpler.

**Review by GaryShen2008 — APPROVED** [review]

**Pull request merged**
