### PR TITLE
add pcbs notebook benchmark

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
add PCBS notebook benchmark

### CODE REVIEW

**Comment by nvliyuan** [comment]
we can ignore the link-checker error, they are not broken.

**Comment by razajafri** [comment]
The instructions aren't clear after running `jupyter notebook` 

It opens a web page with my home folder but doesn't tell me what to do next. Can we add instructions on what the user is supposed to do after running the notebook to run the benchmark?

**Comment by nvliyuan** [comment]
> The instructions aren't clear after running `jupyter notebook`
> 
> It opens a web page with my home folder but doesn't tell me what to do next. Can we add instructions on what the user is supposed to do after running the notebook to run the benchmark?

@razajafri thanks, add two charts to make it more clear

**Comment by nvliyuan** [comment]
@razajafri from the guide I request customers to build the jar, this might cause problems for customers; but if I run the benchmark base on dist plugin jar, I have to import some class like this: 
```
import spark311.org.apache.spark.sql.rapids.GpuInMemoryTableScanExec
```
if customers run on spark312, customers need to change the notebook code. I am not sure if there is a perfect approach to fix this.

**Comment by nvliyuan** [comment]
@razajafri @sameerz  we should not request customers to build the plugin jar for an example, we should use the dist plugin jar, but if we use dist jar, `ParquetCachedBatch` cannot be access by the application code which means that we can not `import spark3xx-common.com.nvidia.spark.rapids.ParquetCachedBatch`, is it possible to expose this class?

**Comment by viadea** [comment]
@razajafri  is there anyway to test using our GA jar?

**Comment by razajafri** [comment]
> @razajafri is there anyway to test using our GA jar?

For now, we have no reason to expose `ParquetCachedBatch`. This is a benchmark that people can run and asking them to build is probably not a stretch IMHO.

**Comment by razajafri** [comment]
@nvliyuan I ran the `PCBS-benchmark.ipynb` but I don't see any output or any mention of where to find the output of the script

**Comment by nvliyuan** [comment]
> @nvliyuan I ran the `PCBS-benchmark.ipynb` but I don't see any output or any mention of where to find the output of the script

The output can be found in the last output cell. 
image
Add a comment in README.md to make it more clear.

**Comment by nvliyuan** [comment]
> For now, we have no reason to expose `ParquetCachedBatch`. This is a benchmark that people can run and asking them to build is probably not a stretch IMHO.

Is there a way we can import the `ParquetCachedBatch` class in notebook without building a jar?

**Comment by nvliyuan** [comment]
close since it is not a benchmark

**Pull request closed without merging**
