### PR TITLE
Adding Databricks tool demo notebooks for qualification and profiling

### PR DESCRIPTION
**Pull request by mattahrens**
Closes https://github.com/NVIDIA/spark-rapids/issues/6782
Closed https://github.com/NVIDIA/spark-rapids/issues/6781

Signed-off-by: Matt Ahrens <matthewahrens@gmail.com>

### CODE REVIEW

**Comment by nvliyuan** [comment]
a typo in qualification notebook:
image
`OUTPUT_DIR = '/tmp/''` -> `OUTPUT_DIR = '/tmp/'`

**Comment by nvliyuan** [comment]
LGTM

**Comment by mattahrens** [comment]
@nvliyuan Thanks for the feedback.  I fixed the typo and added README updates.

**Review by nvliyuan — APPROVED** [review]

**Comment by nvliyuan** [comment]
Hi @mattahrens, could you help re-draft this pr and target to branch-22.12?

**Pull request merged**
