### PR TITLE
Updating Databricks tool example notebooks with output + support for wildcards/S3 as input for qual tool

### PR DESCRIPTION
**Pull request by mattahrens**
Signed-off-by: Matt Ahrens <matthewahrens@gmail.com>

Changes
- Qualification: fix issue with wildcard in input path by converting qual command from python to shell
- Qualification: add in output path widget with S3 download jars included 
- Qualification + Profiler: add sample output to notebooks based on feedback from Karthik

### CODE REVIEW

**Review by tgravescs — COMMENTED** [review]
I would remove mahrens from path names, I would use something more generic like user1

**Comment by tgravescs** [comment]
I tried this out and for some reason it chose 1 thread on an 8 core box. I expected it to use 2 threads per documentation. But even 2 threads is very slow when hundreds of event logs, I'm wondering if we specify that here so users don't see very slow processing

**Comment by mattahrens** [comment]
> I would remove mahrens from path names, I would use something more generic like user1

Done.

**Comment by mattahrens** [comment]
> I tried this out and for some reason it chose 1 thread on an 8 core box. I expected it to use 2 threads per documentation. But even 2 threads is very slow when hundreds of event logs, I'm wondering if we specify that here so users don't see very slow processing

Added in links to documentation for options for qualification and profiling tools.

**Review by tgravescs — APPROVED** [review]

**Pull request merged**
